In [2]:
import numpy as np
import pandas as pd
from Bundle import Bundle as B
import math as m
b = B()
print(b.obj.loc[b.obj['point_id'] == "24"])
print(b.ext.loc[b.ext["image_id"] == "5"])
b.ext[(b.ext["image_id"] == 5) | (b.ext["image_id"] == "5")]["w"]
b.pho['y'].to_list()

b.int

  point_id    X       Y      Z
0       24  0.0  1700.0  100.0
  image_id camera_id      Xc    Yc     Zc     w     o    k
1        5        99  2620.0  90.0  120.0  90.0  40.0  0.0


camera_id        xp        yp         c
0        99  2006.393  1502.312  2031.216

In [1]:
import numpy as np
from Bundle import Bundle as B
b = B()
from Design_e import Design_e as Ae
from Design_o import Design_o as Ao
ae = Ae()
ao = Ao()
ao.rhc
ae.A[0]

matrix([[-3.09479701e-03,  1.18116409e-03,  2.89774687e-04,
          5.94479414e-01, -6.98262317e+00, -5.72627417e-02,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [3]:
import numpy as np
from Design_o import Design_o as Ao
from Net import Network

models = [Ao()]
net = Network(models)
net.obs_0()
net.l_0 - net.obs
net.a_post

LSA passed in: 4 iterations


10.529394797808639

In [2]:
from numpy.linalg import inv
net.set_N()
#net.set_U()
#net.w_0
net.obs_0()
net.update_values()
net.Ae.shape
#net.Ao.shape

xp: 1.7487808500000002 | yp: 1.7152986000000003 | c: 7.0076952 | u: [[32.61497261]] | w: [[-2107.70957044]] | v: [[-17.22295639]]


(322, 24)

In [3]:
net.obs_0()
net.l_0

matrix([[ 1.85721884e+00],
        [ 1.65803586e+00],
        [ 5.45456816e+00],
        [ 1.02533805e+00],
        [ 4.15244621e+00],
        [ 2.85086473e-01],
        [ 5.71055534e+00],
        [ 6.36060695e-01],
        [ 5.04414808e+00],
        [ 4.90954608e+00],
        [-5.09520581e-01],
        [-2.46287861e+00],
        [ 3.66593775e+00],
        [ 1.03782122e+00],
        [ 1.62953720e+00],
        [-7.30585668e-01],
        [ 5.76457435e+00],
        [ 5.07836911e+00],
        [ 2.57796280e+00],
        [ 9.45098295e-03],
        [ 1.51128532e+00],
        [ 6.46796946e+00],
        [ 6.57791899e+00],
        [-2.24044728e-01],
        [ 3.11939451e+00],
        [ 4.25838290e-01],
        [ 4.15569503e+00],
        [ 2.70416333e-01],
        [ 6.40328954e+00],
        [-5.69104474e-01],
        [ 6.26900613e+00],
        [ 3.30191187e+00],
        [ 3.53389287e+00],
        [ 2.09880925e+00],
        [ 4.06570911e+00],
        [ 5.93643846e-01],
        [ 1.78751723e+00],
 

In [4]:
net.x_0_ao[-1]

matrix([[-1334.]])

In [3]:
net.Nee

matrix([[ 1.46992792e+08, -5.64325504e+08, -4.16647036e+08,
         -2.42101786e+12, -1.63073000e+12,  1.40016172e+08,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-5.64325504e+08,  2.16715098e+09,  1.60001772e+09,
          9.28696553e+12,  6.22299197e+12, -3.53684234e+07,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-4.16647036e+08,  1.60001772e