In [2]:
import numpy as np
import pandas as pd
from Bundle import Bundle as B
import math as m
b = B()
print(b.obj.loc[b.obj['point_id'] == "24"])
print(b.ext.loc[b.ext["image_id"] == "5"])
b.ext[(b.ext["image_id"] == 5) | (b.ext["image_id"] == "5")]["w"]
b.pho['y'].to_list()

b.int

  point_id    X       Y      Z
0       24  0.0  1700.0  100.0
  image_id camera_id      Xc    Yc     Zc     w     o    k
1        5        99  2620.0  90.0  120.0  90.0  40.0  0.0


camera_id        xp        yp         c
0        99  2006.393  1502.312  2031.216

In [2]:
import numpy as np
from Bundle import Bundle as B
b = B()
from Design_e import Design_e as Ae
from Design_o import Design_o as Ao
ae = Ae()
ao = Ao()
ao.rhc
ae.A

matrix([[-8.97042612e-01,  3.42366402e-01,  8.39926628e-02, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-8.16206426e-02,  2.13272444e-02,  8.39926628e-02, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-4.25329834e-01,  4.71730668e-01,  4.90829510e-02, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          5.74240573e+02,  2.83481201e+03,  8.04542410e+02],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         -2.12064389e+03,  1.35796385e+01, -6.03601346e+01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         -5.33561131e+01,  2.03300968e+03, -4.56976764e+02]])

In [1]:
import numpy as np
from Design_o import Design_o as Ao
from Net import Network

models = [Ao()]
net = Network(models)

#np.savetxt("w_0.csv", net.w_0, fmt = '%s', delimiter = ",")
net.S_hat

matrix([[ 2.46000000e+02],
        [ 1.52000000e+02],
        [ 3.30125000e+03],
        [ 1.04899379e-01],
        [ 6.20985737e-02],
        [ 1.86458625e-02],
        [-5.50000000e+01],
        [ 3.52000000e+02],
        [ 6.03561753e+18],
        [ 8.91524625e-02],
        [ 2.93907129e-02],
        [-1.14770397e-02],
        [-1.18000000e+02],
        [ 6.00000000e+01],
        [-1.23250000e+02],
        [ 2.41245186e-02],
        [ 1.90606678e-02],
        [ 9.53052853e-03],
        [ 8.23000000e+02],
        [ 2.76000000e+02],
        [ 1.00937500e+03],
        [-2.64033283e-01],
        [ 9.49140991e-02],
        [ 1.55679126e-02],
        [-4.00000000e+00],
        [ 5.20000000e+01],
        [-5.01250000e+01],
        [-2.62221250e+07],
        [ 5.06687680e+07],
        [-1.84262176e+09],
        [-2.50000000e+01],
        [-9.20000000e+01],
        [-2.42500000e+01],
        [-6.00000000e+00],
        [-1.60000000e+01],
        [-4.71250000e+01],
        [-1.00000000e+00],
 

In [2]:
np.concatenate((net.N1,net.Nsym), axis = 1)

matrix([[ 1.84801540e+05, -4.98606742e+04, -1.80254797e+04, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-4.98606742e+04,  1.00760109e+05,  7.62673904e+03, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.80254797e+04,  7.62673904e+03,  3.14510481e+03, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          6.56546055e+04, -4.83766314e+06, -1.18188866e+07],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         -1.15982370e+07,  1.37313761e+06,  1.15108139e+07],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          2.60058102e+06, -4.38431417e+05, -2.89866185e+06]])

In [5]:
from numpy import transpose as t

np.concatenate((t(net.Nsym),net.N2), axis = 1)

matrix([[-8.11347376e-03,  3.08857995e-03,  8.22005327e-04, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 3.08857995e-03, -1.17669605e-03, -3.05475978e-04, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 8.22005327e-04, -3.05475978e-04, -1.41095348e-04, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          1.00013387e+04,  2.73862642e+02, -6.18203100e+03],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          2.73862642e+02,  3.32065767e+03,  4.01480776e+03],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         -6.18203100e+03,  4.01480776e+03,  1.29278112e+04]])

In [13]:
import pandas as pd
pd.concat([b.tie, b.con])

X     Y     Z
point_id                  
24           0  1700   100
71        2200  2500 -1200
85        2800  2000   500
89        2800  2000  -200
132       1800  3000  -800
133       2300  2400  -600
A5          47  1788  1982
B1        1646  3052  1258
B2        2225  2490  1254
B8        1667  3038   489
B9        2215  2506   461
A32       -760   988  -547
A33       -182  1555  -541
A34        392  2122  -547
A35        976  2703  -558
BS8       2559  2177   701
AS10       236  1982  1751
AS12      -381  1373  1464
AS31      -868   889 -1222
AS32       840  2581 -1196
BS11      1585  3128   249
BS17      1767  2956  -796
BS20      2562  2179 -1033
BVS5      2444  2271  1610
BVS6      2212  2498  1613
AVS50       63  1799  1628
AVS51      345  2075  1623
AVS57     -513  1229  1230
AVS58       60  1792  1236
AVS59      630  2361  1248
AVS65     -796   945   776
AVS69      358  2093   784
AVS70      641  2371   777
AVS71      956  2682   797
AVS75     -794   946   402
AVS91     1318  3040    -5
BVS10     1941  2766  1253
BVS16     2747  1983   879
BVS35     2240  2480  -400
BVS36     1598  3109  -358
BVS37     1739  2973  -614
BVS38     2766  1968  -810
BVS42     1605  3101  -868
BVS43     2495  2234 -1205
BVS44     1967  2747 -1192
AVS104    -761   983  -898
AVS105    -476  1261  -874
AVS106    -192  1543  -895
AVS107     101  1834  -885
AVS108     394  2128  -914
AVS116     393  2129 -1352
AVS117     953  2683 -1334